# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: smart_editor 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "smart_editor"
  s.version = "1.0.0"

  # s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Karl Nguyen"]
  s.date = "2014-10-14"
  s.description = "jQuery text editor for Rails App"
  s.email = "thanhkhoait@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/smart_editor.js",
    "app/assets/stylesheets/smart_editor.css",
    "app/assets/stylesheets/smart_editor_fonts/fontawesome-webfont.eot",
    "app/assets/stylesheets/smart_editor_fonts/fontawesome-webfont.svg",
    "app/assets/stylesheets/smart_editor_fonts/fontawesome-webfont.ttf",
    "app/assets/stylesheets/smart_editor_fonts/fontawesome-webfont.woff",
    "lib/generators/smart_editor/install_generator.rb",
    "lib/generators/smart_editor/templates/config/smart_editor.yml",
    "lib/generators/smart_editor/templates/migrations/01_create_smart_editor.rb",
    "lib/generators/smart_editor/templates/migrations/02_add_attachment_image_to_smart_editors.rb",
    "lib/generators/smart_editor/templates/models/smart_editor.rb",
    "lib/smart_editor.rb",
    "smart_editor.gemspec"
  ]
  s.homepage = "https://github.com/ThanhKhoaIT/smart_editor"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "jQuery text editor for Rails App"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

